global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq.Expressions;
global using System.Linq.Dynamic.Core;
global using FreelancersModel.Entity;
global using FreelancersModel.Enum;
global using FreelancersDal.Model;
