namespace FreelancersModel.Enum
{
    public enum ResponseErrorMsgEnum
    {
        UNAUTHORIZE             = -1,
        INVALID_TIMESPAN        = -1001,
        INVALID_SIGNATURE       = -1002,
        INVALID_ACTION          = -1003,
        INVALID_MODEL           = -1004,
        INVALID_OLD_PASSWORD    = -1005,
        INVALID_RESET_TOKEN     = -1006,
        INVALID_MASSAUER_ID     = -1010,
        INVALID_MEMBER_ID       = -1007,
        INVALID_PACKAGE_ID      = -1008,
        INVALID_PACKAGE_AMOUNT  = -1009,
        INVALID_POOL_BID_AMOUNT = -1011,
        INVALID_MEMBER_USERNAME = -1012,
        INVALID_MEMBER_RANK     = -1013,
        INVALID_TRANSACTION     = -1014,
        INVALID_WALLET_TYPE     = -1015,
        INVALID_WITHDRAWAL      = -1016,
        INVALID_KEYWORDS        = -1017,
        INVALID_DATE_RANGE      = -1018,
        INVALID_STATEMENT_DATE  = -1019,
        INVALID_TOPUP_PLAN_ID   = -1020,
        INVALID_DATE            = -1021,
        INVALID_SHOP_ID         = -1022,
        INVALID_ID              = -999,        
        USERNAME_EXIST          = -6001,        
        ADMIN_GROUPNAME_EXIST   = -6002,
        PHONE_EXIST             = -6003,
        REFERRAL_CODE_NOT_EXIST = -6004,
        EMAIL_EXIST             = -6005,
        ICNO_EXIST              = -6006,
        CODE_EXIST              = -6007,
        ROOM_NO_EXIST           = -6008,
        PRODUCT_CODE_EXIST      = -6009,
        PACKAGE_CODE_EXIST      = -6010,
        NOTE_EXIST              = -6011,
        FILE_IS_BLANK           = -8001,
        FILE_NOT_FOUND          = -8002,
        VERIFY_FAILED           = -5001,
        ACCOUNT_INACTIVE        = -5002,
        REQUEST_OTP_TOO_FAST    = -5003,        
        RESET_TOKEN_EXPIRED     = -5004,
        TRANSFER_COMPLETE       = -5005,
        WITHDRAWAL_COMPLETE     = -5006,
        ACCOUNT_SUSPEND         = -5006,
        INSUFFICIENT_AMOUNT     = -7001,
        INSUFFICIENT_CREDIT     = -7002,
        INSUFFICIENT_POINTS     = -7003
    }
}
